### ISSUE TITLE
Classe cliente

### ISSUE THREAD

**Issue by davimartinsfreitas** [DisciplinasProgramacao/poo-tp-2024-1-grupo-filhos-do-atomo#19]
De rascunho do professor João Caram:

@PedroCanuto0811 	Implementar a classe cliente e testar. Caso necessite de outras classes para o teste, você pode fazer uma implementação "fake", mas lembre-se de só subir para o repositório as classes da sua tarefa.

**Comment by davimartinsfreitas** [comment]
Atualização: Tarefa realizada por @davimartinsfreitas - 25/04/2024.

**Comment by joaocaram** [comment]
@ElvisFernando23 corrigir:
- não pode ter set nas propriedades do cliente (uma vez criado, não muda)
- um cliente não tem uma requisição ainda, mas ele pode criar e retorná-la.
