### ISSUE TITLE
Classe requisição

### ISSUE THREAD

**Issue by Vitornocce** [DisciplinasProgramacao/poo-tp-2024-1-grupo-filhos-do-atomo#2]
De rascunho do professor João Caram:

@Vitornocce 		Implementar a classe de requisição/reserva e testar. Caso necessite de outras classes para o teste, você pode fazer uma implementação "fake", mas lembre-se de só subir para o repositório as classes da sua tarefa.

**Comment by joaocaram** [comment]
@Vitornocce quando finalizar a requisição, a mesa deve ser liberada
