### ISSUE TITLE
Atualização da requisição

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/poo-tp-2024-1-grupo-filhos-do-atomo#25]
@hayanness 
Deve receber produtos para pedidos, fechar a conta e exibir valor por cliente.

**Comment by davimartinsfreitas** [comment]
Feito pela Hayanne. Somente aguardando as demais classes das outras tarefas para mescalar com o principal, pois essa tarefa depende da classe Pedido, principalmente.
