### ISSUE TITLE
Atualização do principal

### ISSUE THREAD

**Issue by joaocaram** [DisciplinasProgramacao/poo-tp-2024-1-grupo-filhos-do-atomo#27]
Permitindo ver cardápio, selecionar produto, incluir produto, fechar conta, mostrar conta 
@davimartinsfreitas

**Comment by davimartinsfreitas** [comment]
Feito. Aguardando as demais classes das outras tarefas para mescalar com o principal, pois essa tarefa depende do Restaurante, principalmente. Por enquanto, será mantido em um ramo separado (sprint2).

Outras pendências importantes (ainda da sprint1, que podem exigir refatoração do código)
- A Maneira como está sendo armazenada a requisição (como composição na classe cliente) gera alguns problemas, principalmente por não ser possível a visualização de todas as requisições feitas e para recuperar o cliente associado.

- A fila de espera apresenta um problema pois trava requisições que poderiam ser atendidas, mas não estão na primeira posição da fila. O ideal seria utilizar uma lista.

Vou verificar e tentar corrigir isso tbm.

**Comment by joaocaram** [comment]
> Feito. Aguardando as demais classes das outras tarefas para testar, pois essa tarefa depende do Restaurante, principalmente. Por enquanto, será mantido em um ramo separado (sprint2).

@davimartinsfreitas obrigado por atualizar. Na apresentação eu vou precisar saber quem fez estes ajustes (e seria bom vocês terem isso marcado nos cartões de projeto também)
